### ISSUE TITLE
Documentation / Usage?

### ISSUE THREAD

**Issue by schovi** [xiaody/adblock-minus#1]
Hi

I am just work on personal project, where I have stream of urls and I want to filter them out of  internet "noise" like adwords, autocompleters etc.
Does this project implements url filtering as they are defined in https://easylist.adblockplus.org/en/ and if yes, then how? :)

**Comment by xiaody** [comment]
Yes. Just as the README says, adblock-minus understands most Adblock Plus filters syntax.
And this repo is not only a npm module but also a Chrome extension.

A simple example:
Say you want to block an adware banner on `example.com`, the code would be like:

``` js
var adblock = require('adblock-minus')
adblock.Matcher.addFilter('||adware.com')
var shouldBlock = adblock.Matcher.matchesAny('http://download.adware.com/banner.gif', 'IMAGE', 'example.com') // => true
// to block the request...
```

**Comment by schovi** [comment]
@xiaody Awesome! Thanks a lot
