### ISSUE TITLE
Is it possible to use this in Android?

### ISSUE THREAD

**Issue by hajoxx** [xiaody/adblock-minus#2]
Hey xiaody, thanks for great library. Is it possible to use this in Android WebView? I wonder if "window.chrome" will be there in webkit.

**Comment by xiaody** [comment]
`lib/Adblock.js` is specific to Chrome extension env. It use Chrome extensions' APIs like [chrome.webRequest](https://developer.chrome.com/extensions/webRequest) and [chrome.tabs](https://developer.chrome.com/extensions/tabs) to block requests and insert CSS into web pages.

To judge whether a request should be blocked, you will use the `Matcher` in `lib/Matcher.js`.
see https://github.com/xiaody/adblock-minus/issues/1#issuecomment-186798035 for example.

**Comment by xiaody** [comment]
To do adblocking in native Apps, you may check the projects from [adblock plus](https://github.com/adblockplus/). They have a C++ implementation if I remember correctly.

**Comment by hajoxx** [comment]
Thanks.
