### ISSUE TITLE
How to apply the selectors?

### ISSUE THREAD

**Issue by bittlingmayer** [xiaody/adblock-minus#5]
Assume we have one of the standard lists like easylist.txt.  We split it by `\n`, iterate through add `add`.

Now we have the DOM of a page, and we know the URL.  We wish to apply the selectors we have added to remove the necessary elements.

How to get the selectors to pass to `document.querySelectorAll`?

In the example in the README, the selector is prefixed with a domain.  But in easylist.txt, there are lines like `.admicro.` and `###taboola-ad` with no domain.

**Comment by xiaody** [comment]
Selectors with no domain are generic rules which match all domains.

```js
const adblock = require('adblock-minus')
const blocker = new adblock.Blocker()

blocker.add('##.whatever-banner')
blocker.add('evil.com###adbanner')
for (const selector of blocker.selectors('evil.com')) {
  console.log(selector) // => ['.whatever-banner'], ['#adbanner']
}
```

You can play with it at https://runkit.com/xiaody/adblock-minus

**Comment by bittlingmayer** [comment]
Thanks for the quick reply

That makes sense, but the following outputs only `{}`:

```
const adblock = require('adblock-minus')
const blocker = new adblock.Blocker()

blocker.add('##.whatever-banner')

console.log(blocker.selectors('example.com'));
```

Same if I insert `blocker.add('evil.com###adbanner')`.

In my opinion, it should not be necessary to add a rule for a domain to get the generic rules for all domains.  `blocker.selectors('newandrandom.com')` should return them, and arguably `blocker.selectors()` should work too.

**Comment by xiaody** [comment]
Sure, you don't need to add a domain rule to get the generic rules.

The point is that `blocker.selectors()` returns a generator, not the rules. You must yield the generator to get all the rules.

Check this out:

```js
const adblock = require('adblock-minus')
const blocker = new adblock.Blocker()

blocker.add('##.whatever-banner')
// blocker.add('evil.com###adbanner')
let rules = []
for (const selector of blocker.selectors('evil.com')) {
    rules = rules.concat(selector)
}
console.log(rules) // [".whatever-banner"]
```

**Comment by bittlingmayer** [comment]
Thanks, I had not realised that it was returning a generator.
